# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunga_auth', '0021_tungauser_can_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='tungauser',
            name='category',
            field=models.CharField(blank=True, choices=[(b'developer', 'Developer'), (b'designer', 'Designer')], max_length=20, null=True),
        ),
    ]
